const me = [
  {
    'name': 'Ersan Güvenç',
    'profilePic': 'assets/images/profil_fotografi.jpg',
  },
];

const videocard = [
  {
    'videoname': 'Intermediate Python Programing Course',
    'channelname': 'freeCodeCamp.org',
    'views': '1,7 Mn',
    'videotime': '5:55:47',
    'time': '1 yıl önce',
    'profilePic': 'assets/images/free_code_camp.jpg',
    'videoPic': '',
  },
  {
    'videoname': 'Winning Google Kickstart Round A 2020',
    'channelname': 'William Lin',
    'views': '5,8 Mn',
    'videotime': '17:10',
    'time': '1 yıl önce',
    'profilePic':
        'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60',
    'videoPic': '',
  },
  {
    'videoname':
        "Winter on Fire: Ukraine's Fight for Freedom | Full Feature | Netflix",
    'channelname': 'Netflix',
    'views': '116 B',
    'videotime': '1:37:50',
    'time': '18 saat önce',
    'profilePic': 'assets/images/netflix_logo.png',
    'videoPic': '',
  },
  {
    'videoname': "How Does the Internet Work? - Glad You Asked S1",
    'channelname': 'Vox',
    'views': '1 Mn',
    'videotime': '19:53',
    'time': '2 yıl önce',
    'profilePic': 'assets/images/vox.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Launching a New Earth-Observing Satellite on This Week @NASA – March 4, 2022",
    'channelname': 'NASA',
    'views': '34 B',
    'videotime': '3:07',
    'time': '1 gün önce',
    'profilePic': 'assets/images/nasa.png',
    'videoPic': '',
  },
  {
    'videoname': "DropdownButton (Widget of the Week)",
    'channelname': 'Flutter',
    'views': '24 B',
    'videotime': '1:27',
    'time': '5 gün önce',
    'profilePic': 'assets/images/flutter.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Tesla Q4 and full year 2021 Financial Results and Q&A Webcast",
    'channelname': 'Tesla',
    'views': '206 B',
    'videotime': '1:06:06',
    'time': '1 ay önce',
    'profilePic': 'assets/images/tesla.jpg',
    'videoPic': '',
  },
  {
    'videoname': "Finding Pride in India",
    'channelname': 'Google',
    'views': '22 B',
    'videotime': '1:27',
    'time': '8 gün önce',
    'profilePic': 'assets/images/google.jpg',
    'videoPic': '',
  },
  {
    'videoname': 'Intermediate Python Programing Course',
    'channelname': 'freeCodeCamp.org',
    'views': '1,7 Mn',
    'videotime': '5:55:47',
    'time': '1 yıl önce',
    'profilePic': 'assets/images/free_code_camp.jpg',
    'videoPic': '',
  },
  {
    'videoname': 'Winning Google Kickstart Round A 2020',
    'channelname': 'William Lin',
    'views': '5,8 Mn',
    'videotime': '17:10',
    'time': '1 yıl önce',
    'profilePic':
        'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60',
    'videoPic': '',
  },
  {
    'videoname':
        "Winter on Fire: Ukraine's Fight for Freedom | Full Feature | Netflix",
    'channelname': 'Netflix',
    'views': '116 B',
    'videotime': '1:37:50',
    'time': '18 saat önce',
    'profilePic': 'assets/images/netflix_logo.png',
    'videoPic': '',
  },
  {
    'videoname': "How Does the Internet Work? - Glad You Asked S1",
    'channelname': 'Vox',
    'views': '1 Mn',
    'videotime': '19:53',
    'time': '2 yıl önce',
    'profilePic': 'assets/images/vox.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Launching a New Earth-Observing Satellite on This Week @NASA – March 4, 2022",
    'channelname': 'NASA',
    'views': '34 B',
    'videotime': '3:07',
    'time': '1 gün önce',
    'profilePic': 'assets/images/nasa.png',
    'videoPic': '',
  },
  {
    'videoname': "DropdownButton (Widget of the Week)",
    'channelname': 'Flutter',
    'views': '24 B',
    'videotime': '1:27',
    'time': '5 gün önce',
    'profilePic': 'assets/images/flutter.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Tesla Q4 and full year 2021 Financial Results and Q&A Webcast",
    'channelname': 'Tesla',
    'views': '206 B',
    'videotime': '1:06:06',
    'time': '1 ay önce',
    'profilePic': 'assets/images/tesla.jpg',
    'videoPic': '',
  },
  {
    'videoname': "Finding Pride in India",
    'channelname': 'Google',
    'views': '22 B',
    'videotime': '1:27',
    'time': '8 gün önce',
    'profilePic': 'assets/images/google.jpg',
    'videoPic': '',
  },
  {
    'videoname': 'Intermediate Python Programing Course',
    'channelname': 'freeCodeCamp.org',
    'views': '1,7 Mn',
    'videotime': '5:55:47',
    'time': '1 yıl önce',
    'profilePic': 'assets/images/free_code_camp.jpg',
    'videoPic': '',
  },
  {
    'videoname': 'Winning Google Kickstart Round A 2020',
    'channelname': 'William Lin',
    'views': '5,8 Mn',
    'videotime': '17:10',
    'time': '1 yıl önce',
    'profilePic':
        'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60',
    'videoPic': '',
  },
  {
    'videoname':
        "Winter on Fire: Ukraine's Fight for Freedom | Full Feature | Netflix",
    'channelname': 'Netflix',
    'views': '116 B',
    'videotime': '1:37:50',
    'time': '18 saat önce',
    'profilePic': 'assets/images/netflix_logo.png',
    'videoPic': '',
  },
  {
    'videoname': "How Does the Internet Work? - Glad You Asked S1",
    'channelname': 'Vox',
    'views': '1 Mn',
    'videotime': '19:53',
    'time': '2 yıl önce',
    'profilePic': 'assets/images/vox.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Launching a New Earth-Observing Satellite on This Week @NASA – March 4, 2022",
    'channelname': 'NASA',
    'views': '34 B',
    'videotime': '3:07',
    'time': '1 gün önce',
    'profilePic': 'assets/images/nasa.png',
    'videoPic': '',
  },
  {
    'videoname': "DropdownButton (Widget of the Week)",
    'channelname': 'Flutter',
    'views': '24 B',
    'videotime': '1:27',
    'time': '5 gün önce',
    'profilePic': 'assets/images/flutter.jpg',
    'videoPic': '',
  },
  {
    'videoname':
        "Tesla Q4 and full year 2021 Financial Results and Q&A Webcast",
    'channelname': 'Tesla',
    'views': '206 B',
    'videotime': '1:06:06',
    'time': '1 ay önce',
    'profilePic': 'assets/images/tesla.jpg',
    'videoPic': '',
  },
  {
    'videoname': "Finding Pride in India",
    'channelname': 'Google',
    'views': '22 B',
    'videotime': '1:27',
    'time': '8 gün önce',
    'profilePic': 'assets/images/google.jpg',
    'videoPic': '',
  },
];
